# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Scalar-Quote
version:      0.22
version_from: lib/Scalar/Quote.pm
installdirs:  site
requires:
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
